# app.yaml
runtime: python310  # Use the appropriate Python runtime
entrypoint: gunicorn -b :$PORT app:server
service: dash-test

# Optional: Configure automatic scaling
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

# Optional: Define environment variables
env_variables:
  # Add any environment variables your app requires
  # EXAMPLE_VAR: 'value'

# Handlers for static files (if any)
handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto
